%% add scores to the dataset

load('dat_ten_e.mat')
for i = 1:length(EEG.event)
    subj_i = EEG.event(i).subj;
    ad_i = EEG.event(i).code;
    addr = find(ismember([dat_ten.ad_num], ad_i) & ismember({dat_ten.subj}, subj_i));
    EEG.event(i).score = [...
        dat_ten(addr).q1,...
        dat_ten(addr).q2,...
        dat_ten(addr).q3,...
        dat_ten(addr).q4,...
        dat_ten(addr).q5,...
        dat_ten(addr).q6,...
        dat_ten(addr).q7,...
        dat_ten(addr).q8,...
        dat_ten(addr).q9,...
        dat_ten(addr).q10];
end